export const SKILL_SUGGESTIONS = [
    'Tiếng Anh',
    'Giao tiếp',
    'Làm việc nhóm',
    'Quản lý thời gian',
    'Microsoft Office',
    'Excel',
    'PowerPoint',
    'Word',
    'Photoshop',
    'Illustrator',
    'Canva',
    'Figma',
    'React',
    'JavaScript',
    'Python',
    'Java',
    'HTML',
    'CSS',
    'Customer Service',
    'Bán hàng',
    'Marketing',
    'Content Writing',
    'Dịch thuật',
    'Biên phiên dịch',
    'Giảng dạy',
    'Tư vấn',
    'Nhanh nhẹn',
    'Chăm chỉ',
    'Trách nhiệm',
    'Sáng tạo',
    'Làm việc độc lập',
    'Giải quyết vấn đề',
];

